### ISSUE TITLE
Remove need for private LinkReferenceProvider

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/integration_youtube#1]

**Comment by kyteinsky** [comment]
A class in the app that implements the `IReference` interface similar to `LinkReferenceProvider`? Would it not make sense to include such a class in the OCP since this is a common use case for apps?

**Comment by kyteinsky** [comment]
After porting the `LinkReferenceProvider` to this integration I discovered it doesn't need the opengraph details. The embed does everything for us. Should I port the changes made to `LinkReferenceProvider` to the server code?
