### ISSUE TITLE
Setup release automation

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/integration_youtube#10]
- [x] Create repo https://github.com/nextcloud-releases/integration_youtube
- [x] Enable github actions 
- [x] Setup release action
- [x] Setup release key
- [x] Add nextcloud_release_service as co-maintainer on the app store

**Comment by juliushaertl** [comment]
@kyteinsky Added permissions for you to the release repo, if anyone else from the team needs it let me know

**Comment by kyteinsky** [comment]
@juliushaertl Thanks a lot, that would be it! Maybe transifex setup is also needed. I can push the .tx and .l10nignore files.

**Comment by kyteinsky** [comment]
https://github.com/nextcloud/integration_youtube/pull/11
