### ISSUE TITLE
App link points to wrong github repo

### ISSUE THREAD

**Issue by komoricodrutz** [nextcloud/integration_youtube#12]
Hi,
The installation / update link to this app in the NextCloud points to https://github.com/**juliushaertl**/integration_youtube instead of here.
That linked repo is empty. Thus the install / update fails with guzzle ... 404.
I suspect it was moved from that location to here, but someone forgot to update the link...

Best Regards!

**Comment by juliushaertl** [comment]
Thanks for reporting. I fixed this with removing the accidental created repo on the old url, so the redirect should work again. The URL will also be the new one with the next release after switching to release automation. Can you try again if it works now?
