### ISSUE TITLE
Link picker with search for YouTube videos

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/integration_youtube#4]
We'd need an API key in order to search for videos:

https://developers.google.com/youtube/v3/docs/search/list

Dirty way but likely to break anytime:

https://github.com/appit-online/youtube-search/blob/master/src/lib/search.ts#L6

**Comment by kyteinsky** [comment]
What should we do here? I would prefer the API method to have something solid that doesn't break at the whim of YouTube frontend devs but I am not sure how often it does break.

**Comment by juliushaertl** [comment]
Yep, would agree that the API way is the better one.
