### ISSUE TITLE
Block doubleclick.net

### ISSUE THREAD

**Issue by Luticus** [nextcloud/integration_youtube#5]
Currently when you use embedded videos from youtube it loads in script domains from google, like doubleclick.net which is basically google tracking. Is there anyway to prevent or block this?

**Comment by juliushaertl** [comment]
There is no way we can block what is being loaded in the iFrame as far as I'm aware, but we should probably have a prominent warning in the readme about possible privacy implications

**Comment by Luticus** [comment]
Yea, I was kinda worried this might be the case. I mean noscript is a solution for just me, but I can't rely on every visitor to use that much less know how or have the patients to micromanage that. Not to mention, I really don't like it looking as though doubleclick is coming from my server, which is the illusion that it gives off.

An update to the app store description and documentation warning about that would probably be a good thing.

This is a really cool integration and I'd love to use it, but avoiding things like google tracking is the whole reason I went into using my own server/services in the first place.
